### ISSUE TITLE
To number not valid 

### ISSUE THREAD

**Issue by MarcoDias7** [visualitypl/textris#3] opened 2015-07-24 21:57 UTC
Hi,

I'm able to send SMS this way, but weird thing, it only sends to one user, even if I have 3 users.

My method in User.rb

    def send_daily_sms(user)
        
        @user = user
    
        # put your own credentials here 
        account_sid = 'AC2556499574e7111844811bff28e73061' 
        auth_token = '0593dd8cc063cfbe704bc73a8f83fbba' 
     
        # set up a client to talk to the Twilio REST API 
        @client = Twilio::REST::Client.new account_sid, auth_token 
     
        @client.account.messages.create({
        	:from => '+14234350632', 
        	:to => '+' + @user.phone, 
        	:body => 'SMS journalier',  
        })
      end

My task : 

    task :email_sender_daily => :environment do |_, args|
      User.find_each do |user|
        user.send_daily_sms(user) if user.daily_sms == true && user.phone.present?
      end
    end

So I decided to use the gem Textris to see if using this would work. 

My UserTexter :

    class UserTexter < Textris::Base
      default from: "Our Team <+14234350632>"
    
      def send_daily_sms(user)
        @user = user
        phone = "+" + @user.phone
        puts phone
        text :to => phone
      end
    end

The thing is, I have this in the log :

    +41798352547
    rake aborted!
    Twilio::REST::RequestError: The 'To' number 41798352547 is not a valid phone number.

But as you can see, the number printed in the log is right, and I was doing quite the same when I was using the method in User.rb (it was sending SMS then, but only to one user).

Don't know what to do.

**Comment by ronin** [comment] 2015-07-29 13:58
I think the problem is with Phony.normalize method which strips "+" character from phone number. It looks like twilio gem requires this character. This is only difference from your code. You temporary monkey patch Textris::Delivery::Twilio's class and add "+" in deliver method and check if this works for you.

**Comment by karolsluszniak** [comment] 2016-02-19 11:52
Like @ronin suggested, the problem was using normalized phone number without leading `+` with Twilio. As relevant PR #5 was merged, I'm closing this one.

**Closed by karolsluszniak** 2016-02-19 11:52 UTC
